### ISSUE TITLE
API docs fail to build on edge

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2468]
See https://travis-ci.org/Opentrons/opentrons/builds/440362127?utm_source=github_status&utm_medium=notification

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sphinx/util/inspect.py", line 109, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'opentrons' has no attribute 'Robot'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 526, in import_object
    obj = self.get_attr(obj, part)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 422, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sphinx/util/inspect.py", line 125, in safe_getattr
    raise AttributeError(name)
AttributeError: Robot
/home/travis/build/Opentrons/opentrons/api/docs/source/api.rst:24: WARNING: autodoc: failed to import class 'Pipette' from module 'opentrons.instruments'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 519, in import_object
    __import__(self.modname)
ModuleNotFoundError: No module named 'opentrons.instruments'
```

This was probably broken by https://github.com/Opentrons/opentrons/pull/2395 but does not actually fail builds so it wasn't caught.
